### ISSUE TITLE
Hey i want some help .

### ISSUE THREAD

**Issue by MadDogXD** [Tee-py/raydium-scripts#1]

**Comment by Tee-py** [comment]
What do you need help with?

**Comment by MadDogXD** [comment]
Working on developing a script . Kinda stucked on remove liquidity part . If you can share your telegram id we can talk there and i share my problem there

**Comment by Tee-py** [comment]
Drop your telegram link instead, and I'll give you a chat

**Comment by MadDogXD** [comment]
@S0apy_Smith

**Comment by Tee-py** [comment]
Sent you a dm on there
