### ISSUE TITLE
Adding liquidity

### ISSUE THREAD

**Issue by dmel642** [Tee-py/raydium-scripts#3]
Hello, I'm having problems getting the add liquidity portion of your script to work for me. The swapping works fine however. 

When I create a new market ID for my token, I try to do npm run fetchMarket it returns null. How do I get the pool ID before any liquidity is added? I want to add liquidity for the first time to a pool. Also I had to install node-fetch in order to get the fetching to work.

Also if I want to add lets say 1 billion tokens and like 8 sol in liquidity, where would I enter the 8 sol amount?

Thanks!

**Comment by Tee-py** [comment]
The add liquidity doesn’t work yet. Only works for markets that exists. For the Null fetch issue, I have an updated version that does not depend on the API but depends on reading some data from some of the market info. But that’s not in there. It’s in a private repository. You can read the raydium SDK to find out how to get those information from the amm or market id. https://github.com/raydium-io/raydium-sdk (Check the parse pool info example)
